### ISSUE TITLE
Possible error in 'Some Background Information'

### ISSUE THREAD

**Issue by michaelhiatt** [Patater/manual#1]
Original text follows, entire paragraph pasted:
"So what is a raster display? Put simply, it is just like a television display. A beam of electrons blasts away at the back of a phoshor coated screen in a deterministic way (known as a raster scan). The beam, from the perspective of a person watching the television, travels from left to right, one scan line at a time. The beam never blast electrons from right to left. After the beam reaches the right edge of the screen, it turns off and moves to the right and down one line. When the beam finally reaches the bottom line of the screen, it travels back up to the upper left of the screen and begins this drawing process all over again. Figure 5.1, “The Raster Display” illustrates this process in an exaggerated fashion."

With the description of the scanlines, I believe that it should read: "After the beam reaches the right edge of the screen, it turns off and moves to the LEFT and down one line.".

Apologies if I misunderstood.

Kind Regards,
Michael Hiatt

**Comment by Patater** [comment]
Thanks for catching this mistake.
