### ISSUE TITLE
Add Support for 3DS

### ISSUE THREAD

**Issue by kuashe** [Patater/manual#2]
Hi , thanks for the tutorial . They are very well explained and having the source is great .

Do you have any plan to continue this with 3DS ?

**Comment by Patater** [comment]
That would be nice. I don't have the time to work on that now, but patches are welcome. :)

**Comment by AntonioND** [comment]
But does it really make sense? GBA and NDS are quite similar so it could be ok to make a tutorial for both of them, but the 3DS is completely different.

**Comment by kuashe** [comment]
Looked a bit on the internet . The 3DS is much harder to homebrew . I think it does make sense it supposed to be a tutorial repo, not neccesarly only for the DS .

**Comment by Patater** [comment]
This collection of Nintendo 3DS examples recently came to my attention: https://github.com/devkitPro/3ds-examples

**Comment by kuashe** [comment]
Haa , thank you so much :+1:
